# Problem 1

In [1]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a=np.array([2,3,5,7,8])
# 3 - matris'in boyutunu öğrenin
print(a.shape)
# 4 - matris'i yeniden boyutlandırın
multi=a.reshape(1,5)
print(multi)
# 5 - matris'in boyut sayısını öğrenin
print(a.ndim)

(5,)
[[2 3 5 7 8]]
1


# Problem 2

In [11]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
f=np.array([1,3,5,7,9])
# 2 - Oluşturduğunuz matrisi parçalayın
split=np.split(f,[2,4])
print(split)
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate(split))

[array([1, 3]), array([5, 7]), array([9])]
[1 3 5 7 9]


# Problem 3

In [21]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
matrix=np.random.choice(np.arange(5,101,2),10,replace=False)
print(matrix)
# 2 - matris'in özelliklerini inceleyin
print(matrix.ndim)
print(matrix.size)
print(matrix.shape)
print(matrix.dtype)
matrix.sort()
print(matrix)
print(np.min(matrix))
print(np.max(matrix))

[93  7 57 49 23 91 43 31 19 83]
1
10
(10,)
int64
[ 7 19 23 31 43 49 57 83 91 93]
7
93
